namespace: three-tier-namespace

mongodb:
  replicaCount: 2

  image:
    repository: mongo
    tag: "4.4.6"

  service:
    name: mongodb-svc
    port: 27017

  storage:
    size: 1Gi

secret:
  name: mongo-sec
  username: admin
  password: password123


#backend-deploment
node:
  replicaCount: 2

  image:
    repository: nomandev1011/three-tier-backend
    tag: "latest"
    imagePullPolicy: IfNotPresent

  service:
    name: backend-svc
    port: 3500
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

  env:
    USE_DB_AUTH: true
    PORT: 3500
    MONGO_CONN_STR: mongodb://mongodb-svc:27017/tasksdb?authSource=admin




    #fornted-values
frontend:
  replicaCount: 2

  image:
    repository: nomandev1011/three-tier-frontend
    tag: "latest"
    imagePullPolicy: IfNotPresent

  service:
    name: frontend-svc
    port: 3000
    type: ClusterIP

  env:
    REACT_APP_BACKEND_URL: /api/tasks


#ingress
ingress:
  className: nginx
  host: frontend.local


#HPA
hpa:
  enabled: true

  minReplicas: 2
  maxReplicas: 5

  targetCPUUtilizationPercentage: 50

  