apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{.Values.ingress.className}}
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.service.name }}
                port:
                  number: {{ .Values.frontend.service.port }}
       
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.node.service.name }}
                port:
                  number: {{ .Values.node.service.port }}