apiVersion: v1
kind: Service
metadata:

  name: {{ .Values.node.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.node.service.type }}
  selector:
    app: node
  ports:
    - port: {{ .Values.node.service.port }}
      targetPort: {{ .Values.node.service.port }}