apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.mongodb.service.name }}
  replicas: {{ .Values.mongodb.replicaCount }}

  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb

          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"

          ports:
            - containerPort: {{ .Values.mongodb.service.port }}

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password

          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: {{ .Values.mongodb.storage.size }}